project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  # html:
  #   comments:
  #     hypothesis: true
  #   output-file: "KommentarDatenschutz"
  docx:
    output-file: "KommentarDatenschutz"
    toc: true
    number-sections: false
    highlight-style: github
  # jats:
  #   output-file: "KommentarDatenschutz"
  # pdf:
  #   output-file: "KommentarDatenschutz"
  #   toc: true
  #   number-sections: true
  #   colorlink: true
execute:
  freeze: auto
