project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    output-file: "KommentarDatenschutz"
  docx:
    output-file: "KommentarDatenschutz"
  jats:
    output-file: "KommentarDatenschutz"
  pdf:
    output-file: "KommentarDatenschutz"

execute:
  freeze: auto



